version: '3'

services:
  django:
    build: .
    env_file: ./.env
    ports:
      - '8888:8000'
    volumes:
      - '.:/django-apps'
    # command: python /django-apps/brogproject/manage.py runserver 0:8000
    tty: true
    stdin_open: true